stages:
  - "deploy"

deploy:
  image: ruby:latest
  stage: deploy
  script:
    - composer install
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
  only:
    - main